// gerador das varias paginas a utilizar pela aplicacao
// simaobarroso - 3 marco 2023

exports.genMainPage = function(){ // nao precisa de receber argumentos, a pagina e` independemente do dataset usado
    var data = new Date().toISOString().substring(0,16)

    // experimentar o href com http://localhost:5555/pessoas/

    pagHTML = `

        <!DOCTYPE html>
        <html>
    <head>
        <title>Main Page</title>
        <meta charset = "utf-8"/>
        <link rel="stylesheet" href="w3.css"/> 
    </head>


    <header class="w3-container w3-teal">
        <h1>TPC3 - Engenharia Web</h1>
    </header>


    <ol w3-hoverable class="w3-ul w3-xxlarge">
        <li class="w3-ul w3-hoverable"><a href="/">Lista de Pessoas</a></li>
        <li class="w3-ul w3-hoverable"><a href="/">Distribuicao Por Sexo</a></li>
        <li class="w3-ul w3-hoverable"><a href="/">Distribuicao Por Desporto</a></li>
        <li class="w3-ul w3-hoverable"><a href="/">Top 10 profissoes</a></li>
     </ol>
   

    <footer class="w3-container w3-blue">
      <h5>Generated by pessoas-server : ${data}</h5>
    </footer>
        </body>
    </html>
    `
    return pagHTML
}