// Aqui vao ser precisas ser geradas duas paginas, 
// uma que e` a pagina principal, seguindo a estrutura dita na aula
// uma de criar um utilizador

// usar css para estrutura


exports.sucessPage = function(mode,data) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Sucesso!</title>
        </head>
    <body>
        <h1>Sucesso na sua tarefa!</h1>
    </body>
    <footer class="w3-container w3-pale-blue">
            <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Voltar ao inicio</a>]</h5>
    </footer>
    `

}

exports.mainPage = function(d){

}

exports.formPage= function(d){
    return `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-pale-blue">
                    <h2>Utilizador TO-DO!</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-pale-green w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-pale-blue">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}